
version: "3"
services:

  # service configuration for our database
  database:

    # use the preferred version of the official Postgres image
    # see https://hub.docker.com/_/postgres/
    image: postgres:9.4.5

    # persist the database between containers by storing it in a volume
    volumes:
      - docker-example-postgres:/var/lib/postgresql/data

  # service configuration for our dockerized Rails app
  app:

    # use the Dockerfile next to this file
    build: .
    image: app
    entrypoint: /usr/local/bin/entrypoint.sh
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    working_dir: /var/www/consul

    # makes the app container aware of the DB container
    depends_on:
      - database

    # expose the port we configured Unicorn to bind to
    ports:
      - "3000:3000"
    # map our application source code, in full, to the application root of our container
    volumes:
      - .:/var/www/consul:delegated
      - bundle:/usr/local/bundle:delegated
      # - "$SSH_AUTH_SOCK:/tmp/agent.sock"
    environment:
      - SSH_AUTH_SOCK=/tmp/agent.sock
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true

  smtp:
    image: namshi/smtp

  mailer:
    image: app
    depends_on:
      - database
    entrypoint: /usr/local/bin/entrypoint.sh
    command: bundle exec rake jobs:work
    working_dir: /var/www/consul
    volumes:
      - .:/var/www/consul:delegated
    environment:
      - SSH_AUTH_SOCK=/tmp/agent.sock
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true



volumes:
  docker-example-postgres: {}
  bundle: {}